# Copyright 2026 Salesforce, Inc. All rights reserved.
[package]
name = "output_quality_anomaly_detection"
version = "1.2.0"
rust-version = "1.88.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.anypoint]
group_id = "fa76c43c-f6d0-41fd-bdcd-214ccae74d41"
definition_asset_id = "output-quality-anomaly-detection"
implementation_asset_id = "output-quality-anomaly-detection-flex"

[dependencies]
pdk = { version = "1.10.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
anyhow = "1.0"

[dev-dependencies]
pdk-test = { version = "1.10.0" }
pdk-unit = { version = "1.10.0", features = ["experimental_local_mode"] }
httpmock = "0.6"
reqwest = "0.11"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 'z'
strip = "debuginfo"
